version: '3'

services:
  nexus:
    image: sonatype/nexus3
    environment:
      INSTALL4J_ADD_VM_PARAMS: -Xmx2g
    ports:
      - 8081:8081
    volumes:
      - /data/nexus-data:/nexus-data
    restart: always

